# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/erezcohen/GEANT/NeutronBeam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/erezcohen/GEANT/NeutronBeam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erezcohen/GEANT/NeutronBeam/CMakeFiles /Users/erezcohen/GEANT/NeutronBeam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erezcohen/GEANT/NeutronBeam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NeutronBeam

# Build rule for target.
NeutronBeam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NeutronBeam
.PHONY : NeutronBeam

# fast build rule for target.
NeutronBeam/fast:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/build
.PHONY : NeutronBeam/fast

NeutronBeam.o: NeutronBeam.cc.o
.PHONY : NeutronBeam.o

# target to build an object file
NeutronBeam.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/NeutronBeam.cc.o
.PHONY : NeutronBeam.cc.o

NeutronBeam.i: NeutronBeam.cc.i
.PHONY : NeutronBeam.i

# target to preprocess a source file
NeutronBeam.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/NeutronBeam.cc.i
.PHONY : NeutronBeam.cc.i

NeutronBeam.s: NeutronBeam.cc.s
.PHONY : NeutronBeam.s

# target to generate assembly for a file
NeutronBeam.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/NeutronBeam.cc.s
.PHONY : NeutronBeam.cc.s

src/NeutronBeamActionInitialization.o: src/NeutronBeamActionInitialization.cc.o
.PHONY : src/NeutronBeamActionInitialization.o

# target to build an object file
src/NeutronBeamActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamActionInitialization.cc.o
.PHONY : src/NeutronBeamActionInitialization.cc.o

src/NeutronBeamActionInitialization.i: src/NeutronBeamActionInitialization.cc.i
.PHONY : src/NeutronBeamActionInitialization.i

# target to preprocess a source file
src/NeutronBeamActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamActionInitialization.cc.i
.PHONY : src/NeutronBeamActionInitialization.cc.i

src/NeutronBeamActionInitialization.s: src/NeutronBeamActionInitialization.cc.s
.PHONY : src/NeutronBeamActionInitialization.s

# target to generate assembly for a file
src/NeutronBeamActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamActionInitialization.cc.s
.PHONY : src/NeutronBeamActionInitialization.cc.s

src/NeutronBeamDetectorConstruction.o: src/NeutronBeamDetectorConstruction.cc.o
.PHONY : src/NeutronBeamDetectorConstruction.o

# target to build an object file
src/NeutronBeamDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamDetectorConstruction.cc.o
.PHONY : src/NeutronBeamDetectorConstruction.cc.o

src/NeutronBeamDetectorConstruction.i: src/NeutronBeamDetectorConstruction.cc.i
.PHONY : src/NeutronBeamDetectorConstruction.i

# target to preprocess a source file
src/NeutronBeamDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamDetectorConstruction.cc.i
.PHONY : src/NeutronBeamDetectorConstruction.cc.i

src/NeutronBeamDetectorConstruction.s: src/NeutronBeamDetectorConstruction.cc.s
.PHONY : src/NeutronBeamDetectorConstruction.s

# target to generate assembly for a file
src/NeutronBeamDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamDetectorConstruction.cc.s
.PHONY : src/NeutronBeamDetectorConstruction.cc.s

src/NeutronBeamDetectorMessenger.o: src/NeutronBeamDetectorMessenger.cc.o
.PHONY : src/NeutronBeamDetectorMessenger.o

# target to build an object file
src/NeutronBeamDetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamDetectorMessenger.cc.o
.PHONY : src/NeutronBeamDetectorMessenger.cc.o

src/NeutronBeamDetectorMessenger.i: src/NeutronBeamDetectorMessenger.cc.i
.PHONY : src/NeutronBeamDetectorMessenger.i

# target to preprocess a source file
src/NeutronBeamDetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamDetectorMessenger.cc.i
.PHONY : src/NeutronBeamDetectorMessenger.cc.i

src/NeutronBeamDetectorMessenger.s: src/NeutronBeamDetectorMessenger.cc.s
.PHONY : src/NeutronBeamDetectorMessenger.s

# target to generate assembly for a file
src/NeutronBeamDetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamDetectorMessenger.cc.s
.PHONY : src/NeutronBeamDetectorMessenger.cc.s

src/NeutronBeamEventAction.o: src/NeutronBeamEventAction.cc.o
.PHONY : src/NeutronBeamEventAction.o

# target to build an object file
src/NeutronBeamEventAction.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamEventAction.cc.o
.PHONY : src/NeutronBeamEventAction.cc.o

src/NeutronBeamEventAction.i: src/NeutronBeamEventAction.cc.i
.PHONY : src/NeutronBeamEventAction.i

# target to preprocess a source file
src/NeutronBeamEventAction.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamEventAction.cc.i
.PHONY : src/NeutronBeamEventAction.cc.i

src/NeutronBeamEventAction.s: src/NeutronBeamEventAction.cc.s
.PHONY : src/NeutronBeamEventAction.s

# target to generate assembly for a file
src/NeutronBeamEventAction.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamEventAction.cc.s
.PHONY : src/NeutronBeamEventAction.cc.s

src/NeutronBeamPrimaryGeneratorAction.o: src/NeutronBeamPrimaryGeneratorAction.cc.o
.PHONY : src/NeutronBeamPrimaryGeneratorAction.o

# target to build an object file
src/NeutronBeamPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamPrimaryGeneratorAction.cc.o
.PHONY : src/NeutronBeamPrimaryGeneratorAction.cc.o

src/NeutronBeamPrimaryGeneratorAction.i: src/NeutronBeamPrimaryGeneratorAction.cc.i
.PHONY : src/NeutronBeamPrimaryGeneratorAction.i

# target to preprocess a source file
src/NeutronBeamPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamPrimaryGeneratorAction.cc.i
.PHONY : src/NeutronBeamPrimaryGeneratorAction.cc.i

src/NeutronBeamPrimaryGeneratorAction.s: src/NeutronBeamPrimaryGeneratorAction.cc.s
.PHONY : src/NeutronBeamPrimaryGeneratorAction.s

# target to generate assembly for a file
src/NeutronBeamPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamPrimaryGeneratorAction.cc.s
.PHONY : src/NeutronBeamPrimaryGeneratorAction.cc.s

src/NeutronBeamRunAction.o: src/NeutronBeamRunAction.cc.o
.PHONY : src/NeutronBeamRunAction.o

# target to build an object file
src/NeutronBeamRunAction.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamRunAction.cc.o
.PHONY : src/NeutronBeamRunAction.cc.o

src/NeutronBeamRunAction.i: src/NeutronBeamRunAction.cc.i
.PHONY : src/NeutronBeamRunAction.i

# target to preprocess a source file
src/NeutronBeamRunAction.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamRunAction.cc.i
.PHONY : src/NeutronBeamRunAction.cc.i

src/NeutronBeamRunAction.s: src/NeutronBeamRunAction.cc.s
.PHONY : src/NeutronBeamRunAction.s

# target to generate assembly for a file
src/NeutronBeamRunAction.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamRunAction.cc.s
.PHONY : src/NeutronBeamRunAction.cc.s

src/NeutronBeamTrackerHit.o: src/NeutronBeamTrackerHit.cc.o
.PHONY : src/NeutronBeamTrackerHit.o

# target to build an object file
src/NeutronBeamTrackerHit.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamTrackerHit.cc.o
.PHONY : src/NeutronBeamTrackerHit.cc.o

src/NeutronBeamTrackerHit.i: src/NeutronBeamTrackerHit.cc.i
.PHONY : src/NeutronBeamTrackerHit.i

# target to preprocess a source file
src/NeutronBeamTrackerHit.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamTrackerHit.cc.i
.PHONY : src/NeutronBeamTrackerHit.cc.i

src/NeutronBeamTrackerHit.s: src/NeutronBeamTrackerHit.cc.s
.PHONY : src/NeutronBeamTrackerHit.s

# target to generate assembly for a file
src/NeutronBeamTrackerHit.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamTrackerHit.cc.s
.PHONY : src/NeutronBeamTrackerHit.cc.s

src/NeutronBeamTrackerSD.o: src/NeutronBeamTrackerSD.cc.o
.PHONY : src/NeutronBeamTrackerSD.o

# target to build an object file
src/NeutronBeamTrackerSD.cc.o:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamTrackerSD.cc.o
.PHONY : src/NeutronBeamTrackerSD.cc.o

src/NeutronBeamTrackerSD.i: src/NeutronBeamTrackerSD.cc.i
.PHONY : src/NeutronBeamTrackerSD.i

# target to preprocess a source file
src/NeutronBeamTrackerSD.cc.i:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamTrackerSD.cc.i
.PHONY : src/NeutronBeamTrackerSD.cc.i

src/NeutronBeamTrackerSD.s: src/NeutronBeamTrackerSD.cc.s
.PHONY : src/NeutronBeamTrackerSD.s

# target to generate assembly for a file
src/NeutronBeamTrackerSD.cc.s:
	$(MAKE) -f CMakeFiles/NeutronBeam.dir/build.make CMakeFiles/NeutronBeam.dir/src/NeutronBeamTrackerSD.cc.s
.PHONY : src/NeutronBeamTrackerSD.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... NeutronBeam"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NeutronBeam.o"
	@echo "... NeutronBeam.i"
	@echo "... NeutronBeam.s"
	@echo "... src/NeutronBeamActionInitialization.o"
	@echo "... src/NeutronBeamActionInitialization.i"
	@echo "... src/NeutronBeamActionInitialization.s"
	@echo "... src/NeutronBeamDetectorConstruction.o"
	@echo "... src/NeutronBeamDetectorConstruction.i"
	@echo "... src/NeutronBeamDetectorConstruction.s"
	@echo "... src/NeutronBeamDetectorMessenger.o"
	@echo "... src/NeutronBeamDetectorMessenger.i"
	@echo "... src/NeutronBeamDetectorMessenger.s"
	@echo "... src/NeutronBeamEventAction.o"
	@echo "... src/NeutronBeamEventAction.i"
	@echo "... src/NeutronBeamEventAction.s"
	@echo "... src/NeutronBeamPrimaryGeneratorAction.o"
	@echo "... src/NeutronBeamPrimaryGeneratorAction.i"
	@echo "... src/NeutronBeamPrimaryGeneratorAction.s"
	@echo "... src/NeutronBeamRunAction.o"
	@echo "... src/NeutronBeamRunAction.i"
	@echo "... src/NeutronBeamRunAction.s"
	@echo "... src/NeutronBeamTrackerHit.o"
	@echo "... src/NeutronBeamTrackerHit.i"
	@echo "... src/NeutronBeamTrackerHit.s"
	@echo "... src/NeutronBeamTrackerSD.o"
	@echo "... src/NeutronBeamTrackerSD.i"
	@echo "... src/NeutronBeamTrackerSD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

